### ISSUE TITLE
some mistakes in readme about  then chapter

### ISSUE THREAD

**Issue by QSKOBE24** [google/promises#101]
![image](https://user-images.githubusercontent.com/5968595/54117164-31b8fc00-442b-11e9-9410-c1d572451823.png)

i think  It was negligence to forget the * punctuation。
`
    FBLPromise<NSString *> *chainedStringPromise1 = [numberPromise then:^id(NSNumber *number) {
         return [self stringFromNumber:number];
    }];
`

**Comment by shoumikhin** [comment]
Nice catch @QSKOBE24 !
Do you mind to send a pull request our way with the fix?
Thank you!

**Comment by temrich** [comment]
Thank you for raising the issue. Updated the docs.
