### ISSUE TITLE
how to make catch() to then()?

### ISSUE THREAD

**Issue by SuperMarioBean** [google/promises#103]
hi there, I migrate from PromiseKit to promises recently, and I have a question that is there any way to return a Promise with resolved value to make promise chain go next then(). for example:
```
[self fetchRemoteData]
.then(^id (id rawData) {
 // do result transformed data
    return transformedData
})
.catch(^(NSError *error) {
// get transiformed result from local catch
    return cacheDataWhichHasBeenTransiformed
})
.then(^(id transformedData) {
// dosomething
})
```

**Comment by temrich** [comment]
Hi David, thank you for trying out Promises!

It sounds like [recover](
https://github.com/google/promises/blob/master/g3doc/index.md#recover) is what you are looking for. It allows you to catch an error, address it, and continue the promise chain. 

Please let us know if you have any additional questions.
