### ISSUE TITLE
Too many type arguments for class 'FBLPromise' (have 2, expected 1)

### ISSUE THREAD

**Issue by hejunbinlan** [google/promises#111]
- (FBLPromise<NSData *, NSURLResponse *> *)fetchWithURL:(NSURL *)url {
    return [FBLPromise wrap2ObjectsOrErrorCompletion:^(FBLPromise2ObjectsOrErrorCompletion handler) {
        [NSURLSession.sharedSession dataTaskWithURL:url completionHandler:handler];
    }];
}
compile error：
Too many type arguments for class 'FBLPromise' (have 2, expected 1)

**Comment by temrich** [comment]
Hi @hejunbinlan, in this case, the Promises' `value` would be an `NSArray` containing an `NSData` object and an `NSURLResponse` object. Here's an [example](https://github.com/google/promises/blob/master/Tests/FBLPromisesTests/FBLPromise%2BWrapTests.m).

**Comment by shoumikhin** [comment]
I.e. something like:

```objectivec
- (FBLPromise<NSArray *> *)fetchWithURL:(NSURL *)url {
  return [FBLPromise wrap2ObjectsOrErrorCompletion:^(FBLPromise2ObjectsOrErrorCompletion handler) {
    [NSURLSession.sharedSession dataTaskWithURL:url completionHandler:handler];
  }];
}

// ...

[[object fetchWithURL:...] then:^id(NSArray *result) {
  NSData *data = result.firstObject;
  NSURLResponse *response = result.lastObject;
  //...
}];
```
