### ISSUE TITLE
Is there a C++ version?

### ISSUE THREAD

**Issue by libaineu2004** [google/promises#119]
Is there a C++ version?Suggest a future/promise library implemented in C++, thank you！

**Comment by shoumikhin** [comment]
Hi @libaineu2004,

We though about making a common C core lib with ObjC and Swift wrappers. We can potentially add C++ to that list, of course.

Hope that makes sense.

**Comment by libaineu2004** [comment]
Thank you! Is there a specific project plan?

**Comment by temrich** [comment]
@libaineu2004 not at the moment. We are definitely open to community contributions, if you or anyone else would be interested. :)
