### ISSUE TITLE
implementation discussion: why to use dispatch_group_async along with dispatch_group_enter/leave?

### ISSUE THREAD

**Issue by Josscii** [google/promises#13]
I dug into the source, and found that you use dispatch_group_async along with dispatch_group_enter/leave, is this the right way to use GCD group?

![image](https://user-images.githubusercontent.com/6898115/35774768-312a8162-09b4-11e8-90f9-0a4abeb94d9b.png)

I googled it and find an blog explaining the concept: [Using dispatch groups to wait for multiple web services](http://commandshift.co.uk/blog/2014/03/19/using-dispatch-groups-to-wait-for-multiple-web-services/), it says use either *dispatch_group_async* **OR** *dispatch_group_enter/leave*.

Anyone can explain it?

If it is not appropriate to ask there, sorry for that, I will close it.

**Comment by shoumikhin** [comment]
Thank you for digging into the code, Josscii!
We're always happy to clarify any non-trivial aspects.

The [docs](http://www.manpagez.com/man/3/dispatch_group_async/) mention that `dispatch_group_async` is just a convenience wrapper for `dispatch_group_enter/leave`, so the two are not mutually exclusive.

We use dispatch groups primarily to facilitate [testing](https://github.com/google/promises/blob/master/g3doc/index.md#testing) with [`FBLWaitForPromisesWithTimeout`](https://github.com/google/promises/blob/master/Sources/FBLPromises/FBLPromise%2BTesting.m#L27).

Hope that helps.

**Comment by Josscii** [comment]
Thanks for your information.

It seems that I didn't understand your intention to use `dipatch_group`, sorry for the stupid question. 

Now it becomes more clear, I will read your code and learn more from it.
