### ISSUE TITLE
Contextual type for closure argument list expects 2 arguments, which cannot be implicitly ignored

### ISSUE THREAD

**Issue by akellyak47** [google/promises#132]
Hello,

I'm experiencing some peculiar compiler-related issues.

This example compiles/runs as expected:
```swift
        Promise<PlaceDetailResponse>(on: .global()) {
            return try await(GoogleMapsHTTPClient.getPlaceDetails(placeID: placeID))
        }.then {
            print($0.name)
        }
```

However, if I insert any code (e.g. a print statement) above the above return my code fails to compile with the following error: "Contextual type for closure argument list expects 2 arguments, which cannot be implicitly ignored"

If I take Xcode's suggestion of adding `_,_ in` I get a new error message: "Unexpected non-void return value in void function"

Am I missing something obvious here?

**Comment by shoumikhin** [comment]
Hi @akellyak47,

Please try the following:

```swift
Promise(on: .global()) { () -> PlaceDetailResponse in
  print("hello")
  return try await(GoogleMapsHTTPClient.getPlaceDetails(placeID: placeID))
}.then {
  print($0.name)
}
```

**Comment by akellyak47** [comment]
Hey @shoumikhin,

Thanks for the response. That worked like a charm. As a note, I had to specify `<PlaceDetailResponse>` after `Promise` to remove the following error: "Ambiguous reference to member 'then(on:_:)'". I'm guessing that's a shortcoming with Swift's type inference.
