### ISSUE TITLE
Benchmark compare to ReactiveSwift

### ISSUE THREAD

**Issue by piv199** [google/promises#14]
Hi,

could you please also add ReactiveSwift to benchmark section, because it's also quite popular in iOS community. And it's also interesting to look how does it fit the whole list of stream based third party solutions.

https://github.com/google/promises/blob/master/g3doc/index.md#benchmark

**Comment by shoumikhin** [comment]
Absolutely. Would appreciate if you provide us a code snippet akin we [used for RxSwift](https://gist.github.com/shoumikhin/a3234c2c2801396051a0991992feb3cf) that we could add to the [performance tests](https://github.com/google/promises/blob/master/Tests/PromisesPerformanceTests/Promise%2BThenPerformanceTests.swift).
Thanks!

**Comment by shoumikhin** [comment]
Please reopen the issue when you have the code ready to test for ReactiveSwift. Thanks.
