### ISSUE TITLE
promise.fulfill rejects the promise

### ISSUE THREAD

**Issue by ben-z** [google/promises#140]
I'm encountering a behaviour where calling `promise.fulfill` with an `Error` argument results in the promise being rejected:

```swift
struct SomeError: Error {}

let promise = Promise<Error?>.pending()
promise.then {_ in
    print("Promise fulfilled")
}.catch {_ in
    print("Promise rejected")
}

promise.fulfill(SomeError())
```

The resulting output is `Promise rejected` instead of `Promise fulfilled`. Is this expected behaviour?

It appears that fulfill and reject are not distinguished on the objc layer: https://github.com/google/promises/blob/7373adec497aaf3e18fe0b9c11a39e7b8c1b5337/Sources/Promises/Promise.swift#L57-L64

**Comment by shoumikhin** [comment]
Hi Ben,

Yes, that's made [deliberately](https://github.com/google/promises/blob/master/Sources/FBLPromises/FBLPromise.m#L82), so that a promise cannot be fulfilled with an error, but only rejected.

Thanks.

**Comment by ben-z** [comment]
Hi @shoumikhin,

Thanks for the quick reply! Any idea why this decision was made deliberately? Coming from a Javascript background I was expecting `promise.fulfill` to fulfill the promise regardless of what's passed in.

Thanks

**Comment by shoumikhin** [comment]
Actually, I'd be curious to learn why JS promises allow fulfilling with errors.
Perhaps, because JS is an untyped language and it's not feasible to distinguish between errors and everything else? Or maybe there're real use cases when you want a promise fulfilled with an error?
Don't know. It just seems right to treat a promise resolved with an error as rejected.

**Comment by ben-z** [comment]
That's a very good question that I don't have an answer for 😄. Interesting that it never occurred to me before. I think a use case for fulfilling with an error may occur when we are want a function that asynchronously returns an error object (for passing to other parts of the application):

```swift
let errObj: CustomError? = try? await(getErrorObj())
// use errObj elsewhere
```

or is this just bad programming?

Anyway, the purpose of this issue is fulfilled. I'll close it now.

**Comment by jjc235** [comment]
By the way, this prevents extending a type (i.e. String) to conform to Error- a fulfilled promise with a String return value would be kicked into being rejected.
