### ISSUE TITLE
How to process return value in pass pipeline

### ISSUE THREAD

**Issue by 0x0c** [google/promises#142]
Hello, I want to use `pass` pipeline as mentioned in [Hydra](https://github.com/malcommac/Hydra#pass).
Is there any solution to make it?

**Comment by shoumikhin** [comment]
Hi Akira,

Perhaps [`then`](https://github.com/google/promises/blob/master/g3doc/index.md#then-pipeline) would work just as fine for you?

**Comment by 0x0c** [comment]
@shoumikhin Thank you for your reply! Exactly your suggestion works well.
I'll close this issue. Thank you :)
