### ISSUE TITLE
Cannot install  2.0.0 version

### ISSUE THREAD

**Issue by alexanderkhitev** [google/promises#173]
Hey! I tried to update & clean install of the `PromisesSwift` pod. But CocoaPods installs `PromisesSwift` `1.2.12` version. How can we fix it? Thanks!

**Comment by nsoojin** [comment]
<img width="265" alt="Screenshot 2021-05-11 at 9 59 46 AM" src="https://user-images.githubusercontent.com/3890050/117746879-ba1bcd00-b23f-11eb-9e7a-9ce2904d6a19.png">

It's working fine for me.

**Comment by alexanderkhitev** [comment]
Hey @nsoojin ! I checked it right now, it works thanks!
