### ISSUE TITLE
Benchmark compare to Promise [by @khanlou] 

### ISSUE THREAD

**Issue by own2pwn** [google/promises#19]
Hi,
It would be great to see comparison to [this promice lib](https://github.com/khanlou/Promise). I've ported [Promise+ThenPerformanceTests.swift](https://gist.github.com/own2pwn/d8ee92e9b4bf1223904acc1ed3129965)

**Comment by shoumikhin** [comment]
Sure, the numbers are as follow:

|         Test Case                         |      Time in sec |
|------------------------------|----------------|
| testThenOnSerialQueue          |    0.0000788   |
| testThenOnConcurrentQueue |    0.3029565   |
