### ISSUE TITLE
Please release a new version of promises that includes latest changes for Firebase

### ISSUE THREAD

**Issue by pranjalmd** [google/promises#202]
The latest release tag is [2.1.1](https://github.com/google/promises/releases/tag/2.1.1) (June 23 2022) and latest release is [2.0.0](https://github.com/google/promises/releases/tag/2.0.0) (May 5 2021).

Our team needs a release with [this](https://github.com/google/promises/commit/ae2a31e0adafd0b58eb61edaa9eb5bd800a3a5b0) commit.

PromiseObjC needs a new version release for Firebase:  [FirebaseInstallations](https://cocoapods.org/pods/FirebaseInstallations), [FirebaseMessaging](https://cocoapods.org/pods/FirebaseMessaging), [GoogleUtilities/Environment](https://cocoapods.org/pods/GoogleUtilities), and [FirebaseCore](https://cocoapods.org/pods/FirebaseCore) ,because of the dependency structure.

`FirebaseMessaging > FirebaseInstallations > PromisesObjC`
and 
`FirebaseCore > GoogleUtilities/Environment > PromisesObjC`

**Comment by ykjchen** [comment]
Thanks for the reminder, will handle this weekend.

**Comment by pranjalmd** [comment]
A gentle reminder, @ykjchen !

**Comment by ykjchen** [comment]
Sorry about the delay... started working on the update but ran into issues while pushing to trunk. Will have it in the next couple days.

**Comment by ykjchen** [comment]
Done now (2.2.0). Thanks for your patience.
