### ISSUE TITLE
Promise.all not available

### ISSUE THREAD

**Issue by KristopherGBaker** [google/promises#22]
Promise.all is mentioned in the [documentation](https://github.com/google/promises/blob/master/g3doc/index.md#nested-promises), but it does not appear to be available.

There is an [all](https://github.com/google/promises/blob/master/Sources/Promises/Promise%2BAll.swift) global function, but it only accepts promises of the same type.

[FBLPromise.all](https://github.com/google/promises/blob/master/Sources/FBLPromises/include/FBLPromise%2BAll.h#L33) is not available in Swift.

**Comment by shoumikhin** [comment]
Hi Kristopher,

You're correct, thank you for pointing that out! The documentation was just updated, please take a look and let us know if there's anything we could improve further.

Thanks.
