### ISSUE TITLE
Privacy manifest for sensitive APIs

### ISSUE THREAD

**Issue by nabs-m** [google/promises#225]
Apple recently released a [list of 3rd party SDKs](https://developer.apple.com/support/third-party-SDK-requirements/) that will need to include a privacy manifest by spring 2024. `Promises` is one of them, so I wanted to create an issue to track this so we can update the SDK in consuming apps.

**Comment by lambda123254** [comment]
+1

**Comment by GH-Ong** [comment]
+1 need the privacymanifest as well as code signature for the upcoming apple requirements

**Comment by ykjchen** [comment]
I opened https://github.com/google/promises/pull/226 based on other examples I've found but not quite sure how to test the changes for correctness. Any suggestions?

**Comment by robertjpayne** [comment]
Hi the manifest is available via SwiftPM. I'm debating whether to merge the unofficial support for Cocoapods via resource_bundles or wait for an official statement from them.

**Comment by corentios** [comment]
Following this, a release is planned before spring ? Thanks

**Comment by extstkim** [comment]
Perhaps Firebase team can help since the Firebase SDK ultimately depends on this?

https://github.com/firebase/firebase-ios-sdk/issues/11490

**Comment by ykjchen** [comment]
This is published now in v 2.4.0. Thanks all for your help!
