### ISSUE TITLE
all(), when() with different Promise<Value>

### ISSUE THREAD

**Issue by umbri** [google/promises#23]
How can I use something like this: 
```swift 
let void = Promise<Void>.pending()
let int = Promise<Int>.pending()

when(void, int).then({ (res) in
    print(res)
})

void.fulfill(())
int.fulfill(1)
```
I get this: <img width="572" alt="screen shot 2018-02-14 at 10 47 04" src="https://user-images.githubusercontent.com/17909271/36197588-78bbf2dc-1174-11e8-9bf4-31668a705d7c.png">

Can we implement something like this [example](https://github.com/vadymmarkov/When/blob/d70ca6256be91a749c6b47fbefdec257c9c8cc9f/Sources/When/Functions.swift) 

When using Promises in real world apps this feature is very useful. 
I understand that this will break current API

**Comment by shoumikhin** [comment]
Hey @umbri, I think that's a great idea!
Thank you for bringing it up. Let's implement that and I'll close the issue once it's submitted.

**Comment by shoumikhin** [comment]
Alright, your example should now work since [1.0.3](https://github.com/google/promises/releases/tag/1.0.3). See the updated [docs](https://github.com/google/promises/blob/master/g3doc/index.md#when) and let us know if there're further ways to improve `all` or `when` behavior on your mind.
Enjoy! :)
