### ISSUE TITLE
Question: Correct use of "Broken Chains"

### ISSUE THREAD

**Issue by richardtop** [google/promises#44]
Hi,
I've recently stumbled upon a specific use-case and decided to clarify on the correct use of the _Promises_. The use-case is the need to execute some code on the _promise_ _fulfillment_ and just propagate the error further if the _promise_ has been _rejected_.

**The example**
I'd like to authenticate the user with the _OAuth2 Password Grant_, but keep the implementation details, such as the specific of the Token storage out of the _ViewController_.

So, let's consider, we have a _LoginService_:

```Swift
class LoginService {
  lazy var auth = AuthService()
  lazy var client = RESTClient(accessToken: auth.token)

  func login(username: String = "", password: String = "") -> Promise<String> {
    weak var weakSelf = self
    return client.request(API.authenticate(username: username, password: password)).then({ (token) -> Promise<String> in
      let auth = weakSelf?.auth
      auth?.token = token
      return Promise<String>(token)
    })
  }

  @discardableResult func logOut() -> Promise<Void> {
    auth.eraseAllData()
    return client.request(API.logOut())
  }
}

```

The controller just uses `login` and `logout` methods of the service, while all the token handling is happening under the hood.

The question is, whether such use of _Promises_ is correct, since I add specific logic only on success?

I've read about the [Broken Chain](https://github.com/google/promises/blob/master/g3doc/index.md#broken-chain) antipattern, but would like to hear, whether the provided example is correct/incorrect way to handle such use-cases.

Thank you!
BR,
Richard

**Comment by shoumikhin** [comment]
Hi Richard,

The code looks good. I'd only call out the issue if you possibly get another `login` invocation before the previous request had a chance to complete. May like to store the promise in an optional var and reject it on another `login` attempt. Something like the following:

```swift
class LoginService {
  // ...
  var loginPromise: Promise<String>?

  func login(username: String = "", password: String = "") -> Promise<String> {
    assert(Thread.isMainThread)
    loginPromise?.reject(...)
    auth?.token = ""
    weak var weakSelf = self
    let promise = self.client.request(
      API.authenticate(username: username, password: password)
    ).then { token in
      weakSelf?.auth?.token = token
      weakSelf?.loginPromise = nil
    }
    loginPromise = promise
    return promise
  }
  // ...
}
```

May also consider returning `loginPromise` if it's not nil and the `username` matches the previous invocation. So, everything depends on your use cases.

**Comment by richardtop** [comment]
Thanks for clarifying the issue with another invocation. Practically, it's impossible, as the UI locks immediately before the `login` code is invoked. Other than this, I'm happy to hear that I use the library properly.
