### ISSUE TITLE
Required key CFBundleVersion in Info.plist

### ISSUE THREAD

**Issue by claudiowagner** [google/promises#50]
I try to upload my app and Distribution failed with erros:
- ERROR ITMS-90056: This bundle .../Frameworks/Promises.framework is invalid. The Info.plist file is missign the required key: CFBundleVersion.

The "CFBundleVersion" exists in Info.plist, but is empty. I change manualy to "1" and uploaded my app sucessfuly.

Carthage version: 0.29.0
Promises version: 1.2.1
XCode version: 9.4

**Comment by shoumikhin** [comment]
Thank you for the heads up @claudiowagner!
Please, send a pull-request with proposed changes.

**Comment by shoumikhin** [comment]
Nvm, should be resolved when https://github.com/google/promises/pull/51 is in. Let us know if you see further issues.
Thank you for reporting!
