### ISSUE TITLE
How do I cancel a promise?

### ISSUE THREAD

**Issue by dinghaoz** [google/promises#52]
A use case is autocomplete. When user types, I send out a request to query the completion info but if the user types fast enough, I want to cancel previous sent request before sending the new one.

Thanks

**Comment by shoumikhin** [comment]
Hi @dinghaoz, could you by chance throttle requests on the UI level?
Perhaps something like the following may work?

```swift
func textViewDidChange(_ textView: UITextView) {
  NSObject.cancelPreviousPerformRequests(withTarget: self, selector: #selector(autocomplete(_:)), object: textView)
  perform(#selector(autocomplete(_:)), with: textView, afterDelay: 0.5)
}

@objc
func autocomplete(_ textView: UITextView) {
  // ...
}
```

**Comment by shoumikhin** [comment]
There's some ongoing work to add convenient cancellation to Promises.
But for now, you'd need to use some kind of an outer cancellation token to set when the next request is issued to cancel the current one and probably use such token inside a promise work block to check if any work still needs to be done and stay notified when to bail out. As an option, you may also store a promise somewhere and directly reject it to skip any chained `then` blocks.

**Comment by dinghaoz** [comment]
Thanks @shoumikhin
