### ISSUE TITLE
Using Promises on an application extension

### ISSUE THREAD

**Issue by umdemir** [google/promises#57]
First of all thanks for this beautiful library! I have a small problem with it.

I am trying to use Promises in a network extension and getting these ld warnings:

ld: warning: linking against a dylib which is not safe for use in application extensions: /Users/umit/Desktop/code/meshkat_ios/Carthage/Build/iOS/FBLPromises.framework/FBLPromises
ld: warning: linking against a dylib which is not safe for use in application extensions: /Users/umit/Desktop/code/meshkat_ios/Carthage/Build/iOS/Promises.framework/Promises

According to documentation, submitting my app to iTunes Connect without clearing these warnings will cause a rejection.

https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html

Again from documentation:

"To configure an app extension target to use an embedded framework, set the target’s “Require Only App-Extension-Safe API” build setting to Yes. If you don’t, Xcode reminds you to do so by displaying the warning “linking against dylib not safe for use in application extensions”."

**Comment by shoumikhin** [comment]
Hi Umit, many thanks for reporting the issue!

The good news is Promises doesn't use any non-safe APIs and we do ship app extensions successfully that use Promises internally.

How exactly do you integrate the framework (SwiftPM, CocoaPods, Carthage, etc.)?

I do see we're lacking `APPLICATION_EXTENSION_API_ONLY` flag in [xcodeproj](https://github.com/google/promises/blob/master/Promises.xcodeproj/project.pbxproj) set to `YES`.
Feel free to make the change (see the screenshot attached on which Xcode build option should be toggled) and send us a PR, if that fixes the issue for you.
<img width="587" src="https://user-images.githubusercontent.com/426434/42482324-d894ba92-839b-11e8-924c-8cd3e798939c.png">

If you integrate Promises with CocoaPods, that flags should also be set in your generated project, presumably.

Thanks.

**Comment by umdemir** [comment]
Hi Anthony,

Thanks for quick response! Making the changes and creating a PR were my first reaction actually. But I didn't have permission to push my branch :) If you give my user the required permissions I'd gladly make the changes tomorrow (I left the office).

**Comment by umdemir** [comment]
Oh I think I should fork it and I don’t need permissions

**Comment by temrich** [comment]
Updated in [PR58](https://github.com/google/promises/pull/58).
Thanks, Umit, for the PR!
