### ISSUE TITLE
all() with a generic tuple containing 4 types

### ISSUE THREAD

**Issue by EthanLozano** [google/promises#61]
The `all()` function currently supports tuples with up to [3 different types](https://github.com/google/promises/blob/1.2.3/Sources/Promises/Promise%2BAll.swift#L104). Does it make sense to have an `all()` function that supports tuples with up to 4 types? I realize that if 4 types are supported, then someone might ask for 5 types! So, I understand if this request is denied.

As a workaround, I'm composing `all` within `all`, which isn't pretty: `all(promise1, all(promise2, promise3, promise4))`. FYI, though I'm using 4 promises, my code rarely (if ever) makes 4 I/O requests due to caching.

**Comment by shoumikhin** [comment]
Hi Ethan, we do welcome pull requests :)
I think 4 or even 5 values for ‘all’ should be fine.
