### ISSUE TITLE
Could not cast value of type #MyClass to NSObject

### ISSUE THREAD

**Issue by ingun37** [google/promises#67]
I ran to this runtime error.
Does it mean my class has to be inherited from NSObject to be used as Promise type?

It stops at this library code
```swift
  static func asValue(_ value: AnyObject?) -> Value? {
    // Swift nil becomes NSNull during bridging.
    return value as? Value ?? NSNull() as AnyObject as? Value
  }
```

callstack : 
...
#4	0x000000010f00ccfb in swift::swift_dynamicCastFailure(void const*, char const*, void const*, char const*, char const*) ()
#5	0x000000010f00cd60 in swift::swift_dynamicCastFailure(swift::TargetMetadata<swift::InProcess> const*, swift::TargetMetadata<swift::InProcess> const*, char const*) ()
#6	0x000000010f049d8e in swift_dynamicCastObjCClassUnconditional ()
#7	0x000000010f00f03d in swift_dynamicCast ()
#8	0x000000010f4eaf1a in swift_rt_swift_dynamicCast ()
#9	0x000000010f546f64 in specialized _setDownCastConditional<A, B>(_:) ()
#10	0x000000010f5478c2 in specialized static Set._conditionallyBridgeFromObjectiveC(_:result:) ()
#11	0x000000010f4a792f in static Set._conditionallyBridgeFromObjectiveC(_:result:) ()
#12	0x000000010f4a79a4 in protocol witness for static _ObjectiveCBridgeable._conditionallyBridgeFromObjectiveC(_:result:) in conformance Set<A> ()
#13	0x000000010f0100cd in _dynamicCastClassToValueViaObjCBridgeable(swift::OpaqueValue*, swift::OpaqueValue*, swift::TargetMetadata<swift::InProcess> const*, swift::TargetMetadata<swift::InProcess> const*, (anonymous namespace)::_ObjectiveCBridgeableWitnessTable const*, swift::DynamicCastFlags) ()
#14	0x000000010946f02a in swift_rt_swift_dynamicCast ()
#15	0x000000010947eddd in static Promise.asValue(_:) at $projectpath/Pods/PromisesSwift/Sources/Promises/Promise.swift:104
#16	0x00000001094794d3 in closure #1 in Promise.then(on:_:) at $projectpath/Pods/PromisesSwift/Sources/Promises/Promise+Then.swift:90
#17	0x0000000109479a6d in partial apply for closure #1 in Promise.then(on:_:) ()
#18	0x000000010947823c in thunk for @escaping @callee_guaranteed (@owned Swift.AnyObject?) -> (@out Any?) ()
#19	0x000000010880567e in __56-[FBLPromise chainOnQueue:chainedFulfill:chainedReject:]_block_invoke.88 at $projectpath/Pods/PromisesObjC/Sources/FBLPromises/FBLPromise.m:271
#20	0x00000001088048f5 in __44-[FBLPromise observeOnQueue:fulfill:reject:]_block_invoke_2 at $projectpath/Pods/PromisesObjC/Sources/FBLPromises/FBLPromise.m:224

Thank you.

**Comment by ingun37** [comment]
I tested inheriting NSObject and it worked fine.  I hope theres a solution because I wouldn't like the idea of inheriting unnecessary class.
Thank you

**Comment by shoumikhin** [comment]
Hi @ingun37, could you provide more context, please?
A small code snippet which reproduces the issue for you would be much appreciated!
Also, Xcode and Swift version may be useful.
Thanks!

**Comment by ingun37** [comment]
I found a solution
I changed Promise<Set<MyClass>> to Promise<[MyClass]> and it works fine now
Im satisfied with the solution but I hv made this reproducing unit test code anyway because I would like to watch it gets fixed as much as I love this library.

Xcode version: 9.4.1
Swift version: 4.1

```swift
class MyClass: Hashable, Decodable {
        let s:String
        init(_ s:String) {
            self.s = s
        }
        var hashValue: Int {return s.hashValue}
        static func == (lhs: apiTests.MyClass, rhs: apiTests.MyClass) -> Bool {
            return lhs.s == rhs.s
        }
    }
    
    func testFail() {
        let ex = XCTestExpectation(description: "test")
        Promise { Set([MyClass("a"), MyClass("b")]) }.then { (a)-> Promise<Set<MyClass>> in
            Promise {a}
        }.then {
            print($0)
            ex.fulfill()
        }
        wait(for: [ex], timeout: 10.0)
    }
    func testSuccess() {
        let ex = XCTestExpectation(description: "test")
        Promise { Set([MyClass("a"), MyClass("b")]) }.then {
            print($0)
            ex.fulfill()
        }
        wait(for: [ex], timeout: 10.0)
    }
```

It doesnt break at the exactly same point but I think its the same bug
Thank you
