### ISSUE TITLE
Anyone seeing this asObjCPromise swiftc crash in Xcode 11

### ISSUE THREAD

**Issue by aufflick** [google/promises#71]
for this method:

```swift
  @objc
  public func allFoo() -> Promise<NSArray>.ObjCPromise<NSArray>
  {
    return promiseSwiftArrayOfFoo().then { $0 as NSArray }.asObjCPromise()
  }
```

Crashes swiftc with:

Showing All Messages
```
1.	While generating Objective-C header [redacted]
2.	While printing 'TheClass' at [redacted]/TheClass.swift:14:8
3.	While printing type 'Promise<NSArray>.ObjCPromise<NSArray>'
4.	While printing type 'Value'
```

Update, the original code which also crashes (I thought the above might be simpler for the type mangler to resolve):

```swift
  @objc
  public func allFoo() -> Promise<[Foo]>.ObjCPromise<NSArray>
  {
    return promiseSwiftArrayOfFoo().asObjCPromise()
  }
```

**Comment by aufflick** [comment]
Interesting, a reduced example doesn't cause the compiler crash. I was thinking it might be getting confused by the re-use of `Value`, but in simpler cases it doesn't seem to be the case.

**Comment by shoumikhin** [comment]
Hi Mark,

What if you try something like:

```swift
public func allFoo() -> Promise<[Foo]>.ObjCPromise<NSArray> {
  return promiseSwiftArrayOfFoo().asObjCPromise()
}
```

**Comment by aufflick** [comment]
That was actually what I was doing - I simplified it to use the map in case that helped, both crash in my code.

What does seem to work though is explicitly using `FBLPromise<NSArray>` as the return type. Compiles fine, haven't tested it yet.

**Comment by aufflick** [comment]
Ok, so a current workaround is:

```swift
import Promises
import FBLPromise

  @objc
  public func allFoo() -> FBLPromise<NSArray>
  {
    return promiseSwiftArrayOfFoo().asObjCPromise()
  }
```

Despite requiring the extra import, this actually reads a bit cleaner, so I'm ok with it. Of course `swiftc` shouldn't crash, and I'll keep trying to make a reduced sample that does trigger the crash.

**Comment by shoumikhin** [comment]
Interesting... So you mean if you replace `Promise<[Foo]>.ObjCPromise<NSArray>` return type with `FBLPromise<NSArray>`, it does fix the crash?

**Comment by aufflick** [comment]
Yes.

**Comment by aufflick** [comment]
The crash is in the name mangling/compression code when swiftc is generating the ObjC header, so it sort of makes sense. When the type is a plain ObjC type that code doesn't need to run, it can just use the ObjC type directly.

**Comment by shoumikhin** [comment]
Would you mind to make a small text case demonstrating the issue?
May just edit one of the test files we already have, like `Promise+ThenInteroperabilityTests.swift`, or  create a custom one.
Happy to play with it and see if we can do better.

**Comment by temrich** [comment]
Hey Mark, going to close this issue for now. Feel free to reopen if you have any additional details or can provide a simple test case that repros the issue. Thank you!
