### ISSUE TITLE
Promise fulfil/reject have broken architecture

### ISSUE THREAD

**Issue by virl** [google/promises#74]
Promise class should not have fulfil() and reject() methods — instead, they must be moved to separate class like PromiseSource.

Because currently it is a leak in incapsulation: methods of class that return promises for underlying scheduled operations should not allow fulfillment and rejection of these operations by external user.

**Comment by virl** [comment]
@shoumikhin Yes, all of the above.

Promise and its source (aka Future & Promise in terms of some other implementations) should be separate, so that any API (or any protocol or interface for that matter) that returns the Promise object can be sure that user will not be able to interfere with fulfilment and rejection of that promise by API's internal implementation.

Promises should be read-only objects in the sense that they can only be used to monitor pending error/value, not influence their outcome.

Naturally, it implies separating resolving logic into separate class like PromiseSource that will strongly retain corresponding Promise object (but not the other way around).

**Comment by shoumikhin** [comment]
I think that's an interesting idea. I'll convey it to the rest of folks directly involved into Promises development at Google. Feel free to provide a PR or further details or examples on how you'd like to have that implemented. Thanks again for the suggestion!

**Comment by virl** [comment]
@shoumikhin I don't think there is much to be added in terms of details.

The rationale behind this proposal is the same as with regular mutable/immutable value and value types in general (as in Swift's value types): when you suppling promise as method argument (or returning it from your method) you want to be sure that method's code (or caller of your method) will not be able to interfere with promise's underlying process.

Such interference should be optional and completely separate from Promise class in form of CancelToken #75 (that can also be used for cancellation of async processes, not just unregistration of promise blocks).

**Comment by temrich** [comment]
Hey @virl, I think you bring up a good point about the potential pitfalls of exposing an API that returns a promise that the caller can modify in some way (i.e. by calling fulfill/reject). We are currently looking into potential solutions for addressing this and will hopefully have an update shortly.

Thank you!

**Comment by temrich** [comment]
Hi @virl, please let us know what you think about the proposal made by @shoumikhin in the [comment](https://github.com/google/promises/issues/74#issuecomment-460400519) above. Feel free to reopen this PR if this approach is worth pursuing.

Thank you!
