### ISSUE TITLE
Can't use fulfill with Promise<Void>

### ISSUE THREAD

**Issue by bes** [google/promises#79]
Hi,

I can't figure out how to use fulfill with a `Promise<Void>`.

```
func doSomethingInBackground() -> Promise<Void> {
    return Promise<Void>(on: bgQueue) {
        fulfill, reject in
        myMoc.perform {
            fulfill() // compiler complains Missing argument for parameter #1 in call
        }
    }
}
```

fulfill(nil) doesn't work either.

What is your recommendation on how to initialize an async `Promise` which does not have a logical return value?

**Comment by umbri** [comment]
@bes try 
```
func doSomethingInBackground() -> Promise<Void> {
    return Promise<Void>(on: bgQueue) {
        fulfill, reject in
        myMoc.perform {
             fulfill(())
        }
    }
}
```

**Comment by bes** [comment]
@umbri Thanks, it worked! I tried `fulfill(Void)` before, but as you said it does not seem to work. But `fulfill(())` works.
