### ISSUE TITLE
Type Checking error in catch block does not work as expected

### ISSUE THREAD

**Issue by cyborgthefirst** [google/promises#81]
Suppose one has a scenario where a promise/chain of promises can be potentially rejected with several different error types. 

When switching over the error

```swift
switch error {
case is PromiseError:
    break
default:
    break
}
```

or casting directly

```swift
switch error {
case let error as PromiseError:
    break
default:
    break
}
```

will never succeed. 

This makes it really hard to test for `PromiseError.timedOut`, when other errors need to be handled as well. 

The work around is quite unintuitive as one first needs to cast the error to `NSError` and then check the error domain.

```swift
switch error {
case let error as NSError:
    if error.domain == PromiseError.errorDomain {
        
    }
default:
    break
}
```

If one wants to specifically target the `PromiseError.timedOut` one would need to check for the `PromiseError.timedOut.errorCode` as well.

Am I doing something wrong or is there a specific reason for this?

**Comment by shoumikhin** [comment]
Hi Johannes,

Thanks a lot for reporting this, looks like we forgot to convert the underlying `NSError` to `PromiseError.timedOut` case for the `timeout` operator in Swift.

If you like, feel free to submit a PR with the [fix](https://gist.github.com/shoumikhin/8b755f7510b7d5fe420373d57dac5abd), or use the following workaround to catch `.timedOut` properly:

```swift
switch PromiseError(error) ?? error {
case is PromiseError:
    break
default:
    break
}
```
Thanks!

**Comment by cyborgthefirst** [comment]
Hi Anthony, 

thank you for your response.
I will submit a PR. 

Thank you for your support
