### ISSUE TITLE
Copy / Paste code from documentation produces error upon build

### ISSUE THREAD

**Issue by trinhhunganh** [google/promises#84]
Copy and Paste the following code sample produces "Unable to infer complex closure return type; add explicit type to disambiguate" error when building swift 4.2 project in latest XCode
https://github.com/google/promises/blob/858556294729f7391ef94f0c8f86c216553bdfc8/g3doc/index.md#catch-pipeline

**Comment by shoumikhin** [comment]
Thanks for reporting, Trinh!

Feel free to send a pull request our way with the fix:

```swift
func work2(_ string: String) -> Promise<Int> {
  return Promise { () -> Int in
    guard let number = Int(string), number > 0 else { throw CustomError() }
    return number
  }
}
```

Thanks.

**Comment by temrich** [comment]
Fixed in [PR85](https://github.com/google/promises/pull/85).
Thank you!
