### ISSUE TITLE
Problem with typing 

### ISSUE THREAD

**Issue by nateuni** [google/promises#89]
Firstly is there any IRC channel where I can go and ask questions? I have looked everywhere and have run out of options, so I will ask here if I may? I am refactoring previously working code over to having promises, and I am trying to understand what is going on and how to fix a typing error. To qualify, I am actually a Product Manager that studied CS that is working on my side project, so bare with me.

In my code: I have this execution flow of Promises as [shown in this gist](https://gist.github.com/nateuni/99642bc2e7666d2b896f55ecdbf5b3e9).

I can see that the nested promises are called but not recognised in the outer promise chain, as the Always executes before the nested promises do.  And whilst executing the nested promises the: `self.saveUserProfilePictureToFirestore(user: user, profileImage: image).then` function never returns a promise from its closure, it just hangs. I believe this is because I need to make that initial call to the nested promises with a with `return self.makeFacebookGraphRequest(accessToken: token).then`. But when I do I get `"Unexpected non-void return value in void function"` error message on the last nested .then, I have tried all types of things and even got a mobile dev from work to try and help me and he too couldn't figure it out. 

What am I missing here?

**Comment by shoumikhin** [comment]
Hi @nateuni,

Technically, we have a [chat on Gitter](https://gitter.im/google/promises). There's a corresponding badge about that in Readme. But you're more than welcome to post your questions as issues here.

Try to place a `return` statement in front of `self.makeFacebookGraphRequest`:

```swift
// ...
}.then { token, document in
  if document?.exists == false {
    return self.makeFacebookGraphRequest(accessToken: token).then { user in
      return self.downloadFacebookProfilePictureAsImage(userModel: user)
    }.then { user, image in
// ...
```

Ideally, you want to refactor that nested piece into a separate function to avoid nesting promises, then use it approximately like so:

```swift
// ...
}.then { token, document in
  return document?.exists ? self.dismiss(animated: true, completion: nil) : self.loginUser(with: token)
}.catch { error in
// ...
```

Thanks.

**Comment by nateuni** [comment]
So I made this changes: 
`}.then { (arg) in
                let (token, document) = arg
                return document?.exists ? self.dismiss(animated: true, completion: nil) : self.createNewUserAccount(token: token)`

But I still get _Unexpected non-void return value in void function_. I have tried: 

1. Wrapping the dismiss in the function that returns a promise.
2. Having Promise<Void> return types 

Maybe my functions aren't setup correctly:

`internal func createNewUserAccount(token: AccessToken) -> Promise<Void> {
        return Promise { fulfill, reject in
            return self.makeFacebookGraphRequest(accessToken: token).then { user in
                // this goes to facebook gets the user details and instantiates a User model
                // returns a Promise<User>
                return self.downloadFacebookProfilePictureAsImage(userModel: user)
                // this goes and gets a profile image from facebook for the given user and returns it as a UIImage
                }.then { user, image in
                    // BUG IN THIS FUNCTION!!
                    return self.saveUserProfilePictureToFirestore(user: user, profileImage: image)
                    // TODO: this should return the URL for where is was saved! (currently this is two seperate functions)
                }.then { user in
                    //BUG ??NEVER REACHED!!
                    return self.getProfilePictureUrlFromFirestoreForUser(user: user)
                }.then { user, imageUrl in
                    // this takes in a user model and creates a Firebase user record
                    return self.createNewUserDocumentAsDictionary(user: user, avatarUrl: imageUrl)
                }.then { user, userDictionary in
                    // TODO: Jimmy to make sabe signup date on BE.
                    return self.saveUserDocumentToFirestore(user: user, data: userDictionary)
                }.then {
                    // Continue sign in flow
                    fulfill(())
                    self.performSegue(withIdentifier: "TermsViewController", sender: self)
            }
        }
    }`

**Comment by shoumikhin** [comment]
What do you get for the following code?

```swift
}.then { token, document in
  document?.exists
      ? wrap { self.dismiss(animated: true, completion: $0) }
      : self.createNewUserAccount(token: token)
}.catch { error in
```
```swift
private func createNewUserAccount(token: AccessToken) -> Promise<Void> {
  return makeFacebookGraphRequest(accessToken: token).then { user in
    self.downloadFacebookProfilePictureAsImage(userModel: user)
  }.then { user, image in
    self.saveUserProfilePictureToFirestore(user: user, profileImage: image)
  }.then { user in
    self.getProfilePictureUrlFromFirestoreForUser(user: user)
  }.then { user, imageUrl in
    self.createNewUserDocumentAsDictionary(user: user, avatarUrl: imageUrl)
  }.then { user, userDictionary in
    self.saveUserDocumentToFirestore(user: user, data: userDictionary)
  }.then {
    self.performSegue(withIdentifier: "TermsViewController", sender: self)
  }
}
```

Note: when a closure has only one statement, it can technically skip the `return` statement.
If you still have compiler error, please, specify at which line it occurred.

**Comment by nateuni** [comment]
I will show both functions together as maybe it will give more context and I left the comments in about the return types. 

```swift
    /// this is called when the user clicks the login button.
    private func flow(){
        //this gets valid facebook token for the app
        loginToFacebook().then {token in
            // returns Promise<AccessToken>
            // with the token we can sign into Firebase
            return self.signIntoFirebase(accessToken: token)
            // returns Promise<AccessToken>
        }.then { token in
            // we need to token to get the userId for the logged in user
            return self.getUserDocumentFromFirebase(userId: token.userId!)
            // returns Promise<(AccessToken, DocumentSnapshot?)>
        }.then { token, document in
            return document?.exists ? self.dismiss(animated: true, completion: nil) : self.createNewUserAccount(token: token)
        }.catch { error in
            self.log.error(error.localizedDescription)
        }.always {
            Dependency.dismissHud(self.hud, "Test title", "Test message text", 3)
        }
    }
    
    private func createNewUserAccount(token: AccessToken) -> Promise<Void> {
        return makeFacebookGraphRequest(accessToken: token).then { user in
            self.downloadFacebookProfilePictureAsImage(userModel: user)
            }.then { user, image in
                self.saveUserProfilePictureToFirestore(user: user, profileImage: image)
            }.then { user in
                self.getProfilePictureUrlFromFirestoreForUser(user: user)
            }.then { user, imageUrl in
                self.createNewUserDocumentAsDictionary(user: user, avatarUrl: imageUrl)
            }.then { user, userDictionary in
                self.saveUserDocumentToFirestore(user: user, data: userDictionary)
            }.then {
                self.performSegue(withIdentifier: "TermsViewController", sender: self)
        }
    }
 ```

Currently with that code I get this error: `Closure tuple parameter '(AccessToken, DocumentSnapshot?)' does not support destructuring` for the `}.then { token, document in` line. Xcode give me a automated fix which results in the tuple being converted like:

```swift 
}.then { (arg) in
                
                let (token, document) = arg
                return document?.exists ? self.dismiss(animated: true, completion: nil) : self.createNewUserAccount(token: token)
        }.catch { error in
```
That gets rid of that error. When I do this change that you suggested:
```swift
}.then { token, document in
  document?.exists
      ? wrap { self.dismiss(animated: true, completion: $0) }
      : self.createNewUserAccount(token: token)
}.catch { error in
``` 
I get `Result values in '? :' expression have mismatching types 'Promise<Any?>' and 'Promise<Void>'` with `self.createNewUserAccount(token: token)` underlined.

**Comment by shoumikhin** [comment]
Would it help if you specify the return type explicitly?
It should be `Promise<Void>`, but not `Promise<Any?>`.

```swift
}.then { (token, document) -> Promise<Void> in
  document?.exists
      ? wrap { self.dismiss(animated: true, completion: $0) }
      : self.createNewUserAccount(token: token)
}.catch { error in
```

I have no idea how `saveUserDocumentToFirestore()` does what it does under the hood. Perhaps it must be called on a background dispatch queue, because it blocks the caller (main) queue in that `putData()` you've mentioned?

Doesn't seem there's a need of a pending promise anywhere.

**Comment by nateuni** [comment]
I will try playing around with where it is dispatched. 

Even with 

```swift
}.then { (arg) -> Promise<Void> in
            let (token, document) = arg
            document?.exists
                ? wrap { self.dismiss(animated: true, completion: $0) }
                : self.createNewUserAccount(token: token)
        }.catch { error in
```

Fro `: self.createNewUserAccount(token: token)` I still get `Result values in '? :' expression have mismatching types 'Promise<Any?>' and 'Promise<Void>'`

**Comment by nateuni** [comment]
I still don't understand why the Always is getting called before `self.createNewUserAccount(token: token)` and all the nested promises have finished. 

```swift
    private func flow(){
        loginToFacebook().then {token in
            return self.signIntoFirebase(accessToken: token)
        }.then { token in
            return self.getUserDocumentFromFirebase(userId: token.userId!)
        }.then { token, document in
            return document?.exists ? self.dismiss(animated: true, completion: nil) : self.createNewUserAccount(token: token)
        }.catch { error in
            self.log.error(error.localizedDescription)
        }.always {  //<-- This executes before self.createNewUserAccount(token: token) finishes.
            Dependency.dismissHud(self.hud, "Test title", "Test message text", 3)
        }
    }
    
    private func createNewUserAccount(token: AccessToken) -> Promise<Void> {
        return makeFacebookGraphRequest(accessToken: token).then { user in
            self.downloadFacebookProfilePictureAsImage(userModel: user)
            }.then { user, image in
                self.saveUserProfilePictureToFirestore(user: user, profileImage: image)
            }.then { user in
                self.getProfilePictureUrlFromFirestoreForUser(user: user)
            }.then { user, imageUrl in
                self.createNewUserDocumentAsDictionary(user: user, avatarUrl: imageUrl)
            }.then { user, userDictionary in
                self.saveUserDocumentToFirestore(user: user, data: userDictionary)
            }.then {
                self.performSegue(withIdentifier: "TermsViewController", sender: self)
        }
    }
```

**Comment by shoumikhin** [comment]
Awesome!

Do you mind to share the code snippet with the fix?
At least the one where you specified the return type.

Thanks.

**Comment by nateuni** [comment]
Sure. 

Here was the issue [that I found for the Firebase Storage](https://github.com/firebase/firebase-ios-sdk/issues/1888). Lesson: update yours pods.  

As for the typing:

```swift
 private func flow(){
        self.log.info("->")
        loginToFacebook().then {token in
            return self.signIntoFirebase(accessToken: token)
        }.then { token in
            return self.getUserDocumentFromFirebase(userId: token.userId!)
        }.then { (arg) -> Promise<Void> in
            let (token, document) = arg
            if document?.exists == true {
                return wrap { self.dismiss(animated: true, completion: $0) }
            } else {
                return self.createNewUserAccount(token: token)
            }
        }.catch { error in
            self.log.error(error.localizedDescription)
        }.always {
            Dependency.dismissHud(self.hud, "", "", 1.5)
        }
        self.log.info("<-")
    }
    
    private func createNewUserAccount(token: AccessToken) -> Promise<Void> {
        hud.textLabel.text = "Creating new user account"
        self.log.info("<>")
        return makeFacebookGraphRequest(accessToken: token).then { user in
            self.downloadFacebookProfilePictureAsImage(userModel: user)
        }.then { user, image in
            self.saveUserProfilePictureToFirestore(user: user, profileImage: image)
        }.then { user in
            self.getProfilePictureUrlFromFirestoreForUser(user: user)
        }.then { user, imageUrl in
            self.createNewUserDocumentAsDictionary(user: user, avatarUrl: imageUrl)
        }.then { user, userDictionary in
            self.saveUserDocumentToFirestore(user: user, data: userDictionary)
        }.then {
            self.performSegue(withIdentifier: "TermsViewController", sender: self)
        }
    }
```
